[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nitroglyph"
version = "0.1.1"
description = "Python bindings for NitroGlyph"
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/adhilsalim/nitro-glyph"
Source = "https://github.com/adhilsalim/nitro-glyph"

[tool.setuptools.packages.find]
where = ["."]
include = ["nitroglyph*"]
